# Inspecting cell-ranger outputs

In [ ]:
#imports
import h5py
from scipy.io import mmread

In [20]:
# load file
path_to_M11_file = "/Users/Akanksha/JugnuLab/data_analysis/datasets/snRNA_ERCC1_KO_MF/raw_data/M11/filtered_feature_bc_matrix.h5"
f = h5py.File(path_to_M11_file, 'r')

# display groups
group_keys = list(f.keys())
print(group_keys)

# move to gubgroups
all_data = f['matrix']
subgroup_keys = list(all_data.keys())
print(subgroup_keys)

# get individual datasets
barcodes = all_data['barcodes'] #no. of unique cell barcodes
data = all_data['data'] #stores ONLY non-zero values in the data matrix
indices = all_data['indices'] #indicates which feature each non-zero element value in the data matrix maps to for all cells
indptr = all_data['indptr'] #indicates where in the data matrix each cell's feature starts
shape = all_data['shape'] 

# display datasets
print(barcodes) 
print(data) 
print(indices)
print(indptr)

#convert to numpy arrays
barcodes = barcodes[()]
data = data[()]
indices = indices[()]
indptr = indptr[()]

# display datasets
print(barcodes)
print(data)
print(indices)
print(indptr)


['matrix']
['barcodes', 'data', 'features', 'indices', 'indptr', 'shape']
<HDF5 dataset "barcodes": shape (8239,), type "|S18">
<HDF5 dataset "data": shape (12541500,), type "<i4">
<HDF5 dataset "indices": shape (12541500,), type "<i8">
<HDF5 dataset "indptr": shape (8240,), type "<i8">
[b'AAACCCAAGCCGCTTG-1' b'AAACCCAAGTCCTGTA-1' b'AAACCCAGTAGACGTG-1' ...
 b'TTTGTTGTCGAAGTGG-1' b'TTTGTTGTCGAGAGCA-1' b'TTTGTTGTCGCCTAGG-1']
[1 3 2 ... 1 2 1]
[   38    40    47 ... 32203 32204 32207]
[       0     1697     3308 ... 12537716 12539747 12541500]


In [25]:
#load feature_by_cell mtx
path_to_M11_mtx = "/Users/Akanksha/JugnuLab/data_analysis/datasets/snRNA_ERCC1_KO_MF/raw_data/M11/filtered_feature_bc_matrix/matrix.mtx"
M11_mtx = mmread(path_to_M11_mtx)

# display mtx shape
print(M11_mtx.shape)


(32285, 8239)
